name: loop_tf
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - pip=21.2.4
  - setuptools==63.2.0
  - python=3.8.12
  - pytorch=1.11.0
  - protobuf==3.20.1
  - pip:
    - jupyter==1.0.0
    - matplotlib==3.5.2
    - numpy==1.22.3
    - pandas==1.4.2
    - quinine==0.3.0
    - tqdm==4.64.0
    - wandb==0.12.11
    - ipdb
